blueprint:
  name: Sonoff Button State Change
  description: Detects state changes for Sonoff button 2
  domain: automation
  input:
    sonoff_button:
      name: Sonoff Button
      selector:
        device:
          filter:
          - manufacturer: eWeLink
            model: WB01
          - manufacturer: eWeLink
            model: SNZB-01P
          - manufacturer: SONOFF
            model: SNZB-01P
          multiple: false
trigger:
  platform: event
  event_type: state_changed
  event_data:
    entity_id: !input sonoff_button

condition: []

action:
  - service: notify.notify
    data:
      message: >
        Sonoff button 2 state changed from {{ trigger.event.data.old_state.state }} to {{ trigger.event.data.new_state.state }}
