blueprint:
  name: ZHA - Sonoff SNZB-01
  description: 'Perform actions with the Sonoff SNZB-01 Button. You can set functions for single press, double press and hold. This allows you to assign, e.g., a scene or anything else.'
  domain: automation
  input:
    remote:
      name: Remote
      description: Sonoff Button to use
      selector:
        entity:
          domain: sensor
          multiple: false
    single_press:
      name: Single press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    hold:
      name: Hold
      description: Action to run on hold
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input remote
action:
  - variables:
      old_state: '{{ trigger.event.data.old_state.state }}'
      new_state: '{{ trigger.event.data.new_state.state }}'
  - choose:
      - conditions:
          - '{{ old_state == "single" and new_state == "" }}'
        sequence: !input 'single_press'
      - conditions:
          - '{{ old_state == "double" and new_state == "" }}'
        sequence: !input 'double_press'
      - conditions:
          - '{{ old_state == "hold" and new_state == "" }}'
        sequence: !input 'hold'
